# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opendwarf/proto/CoreProtocol.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'opendwarf/proto/CoreProtocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"opendwarf/proto/CoreProtocol.proto\x12\x07\x64\x66proto\"\x82\x03\n\x10\x43oreTextFragment\x12\x0c\n\x04text\x18\x01 \x02(\t\x12.\n\x05\x63olor\x18\x02 \x01(\x0e\x32\x1f.dfproto.CoreTextFragment.Color\"\xaf\x02\n\x05\x43olor\x12\x0f\n\x0b\x43OLOR_BLACK\x10\x00\x12\x0e\n\nCOLOR_BLUE\x10\x01\x12\x0f\n\x0b\x43OLOR_GREEN\x10\x02\x12\x0e\n\nCOLOR_CYAN\x10\x03\x12\r\n\tCOLOR_RED\x10\x04\x12\x11\n\rCOLOR_MAGENTA\x10\x05\x12\x0f\n\x0b\x43OLOR_BROWN\x10\x06\x12\x0e\n\nCOLOR_GREY\x10\x07\x12\x12\n\x0e\x43OLOR_DARKGREY\x10\x08\x12\x13\n\x0f\x43OLOR_LIGHTBLUE\x10\t\x12\x14\n\x10\x43OLOR_LIGHTGREEN\x10\n\x12\x13\n\x0f\x43OLOR_LIGHTCYAN\x10\x0b\x12\x12\n\x0e\x43OLOR_LIGHTRED\x10\x0c\x12\x16\n\x12\x43OLOR_LIGHTMAGENTA\x10\r\x12\x10\n\x0c\x43OLOR_YELLOW\x10\x0e\x12\x0f\n\x0b\x43OLOR_WHITE\x10\x0f\"D\n\x14\x43oreTextNotification\x12,\n\tfragments\x18\x01 \x03(\x0b\x32\x19.dfproto.CoreTextFragment\"\x0e\n\x0c\x45mptyMessage\"\x1b\n\nIntMessage\x12\r\n\x05value\x18\x01 \x02(\x05\"\"\n\x11StringListMessage\x12\r\n\x05value\x18\x01 \x03(\t\"X\n\x0f\x43oreBindRequest\x12\x0e\n\x06method\x18\x01 \x02(\t\x12\x11\n\tinput_msg\x18\x02 \x02(\t\x12\x12\n\noutput_msg\x18\x03 \x02(\t\x12\x0e\n\x06plugin\x18\x04 \x01(\t\"$\n\rCoreBindReply\x12\x13\n\x0b\x61ssigned_id\x18\x01 \x02(\x05\";\n\x15\x43oreRunCommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x02(\t\x12\x11\n\targuments\x18\x02 \x03(\t\"H\n\x11\x43oreRunLuaRequest\x12\x0e\n\x06module\x18\x01 \x02(\t\x12\x10\n\x08\x66unction\x18\x02 \x02(\t\x12\x11\n\targuments\x18\x03 \x03(\tB\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opendwarf.proto.CoreProtocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_CORETEXTFRAGMENT']._serialized_start=48
  _globals['_CORETEXTFRAGMENT']._serialized_end=434
  _globals['_CORETEXTFRAGMENT_COLOR']._serialized_start=131
  _globals['_CORETEXTFRAGMENT_COLOR']._serialized_end=434
  _globals['_CORETEXTNOTIFICATION']._serialized_start=436
  _globals['_CORETEXTNOTIFICATION']._serialized_end=504
  _globals['_EMPTYMESSAGE']._serialized_start=506
  _globals['_EMPTYMESSAGE']._serialized_end=520
  _globals['_INTMESSAGE']._serialized_start=522
  _globals['_INTMESSAGE']._serialized_end=549
  _globals['_STRINGLISTMESSAGE']._serialized_start=551
  _globals['_STRINGLISTMESSAGE']._serialized_end=585
  _globals['_COREBINDREQUEST']._serialized_start=587
  _globals['_COREBINDREQUEST']._serialized_end=675
  _globals['_COREBINDREPLY']._serialized_start=677
  _globals['_COREBINDREPLY']._serialized_end=713
  _globals['_CORERUNCOMMANDREQUEST']._serialized_start=715
  _globals['_CORERUNCOMMANDREQUEST']._serialized_end=774
  _globals['_CORERUNLUAREQUEST']._serialized_start=776
  _globals['_CORERUNLUAREQUEST']._serialized_end=848
# @@protoc_insertion_point(module_scope)
