"""System and turn prompts for the tactical decision LLM.

The action list is now generated by the action registry (opendwarf.actions),
not hand-rolled here. This module builds the cache-friendly system PromptBundle
and the per-turn user message.
"""

from __future__ import annotations

from opendwarf.llm.base import Block, PromptBundle

_SYSTEM_BASE = """\
You are an AI playing Dwarf Fortress in Adventure Mode. You control an adventurer \
exploring the world, fighting enemies, talking to NPCs, and completing quests.

You receive a summary of the current game state each turn and must choose ONE action \
from the listed available actions.

The map is a top-down view around you (@ = you):
  . floor   # wall   + door   < up-stair   > down-stair   ~ water
  ^ ramp (slope connecting z-levels — walk onto it to go up/down hills)
  u friendly unit    h hostile unit    ? unexplored
Pathfinding handles walls and routing for you — prefer goto_site / goto_unit / \
explore over single steps for travel. Use move_* only for precise positioning.
Towns and wilderness are often hilly: if you seem walled in, the way out is \
usually a ramp (^) or stairs; explore and goto handle ramps automatically.

Maintain a scratchpad of notes across turns: your current intent, what you've \
tried and how it went, and durable facts (e.g. "Ironhold's north gate is barred"). \
Rewrite it each turn via the optional "scratchpad" field, carrying forward what \
still matters and dropping what's stale.

You also maintain a Policy: standing orders that autopilot behaviors execute \
without consulting you (which species to engage, when to flee, eat/drink/sleep \
rules, hard "never" rules). The current policy is shown each turn. Revise it via \
the optional "policy" field with ONLY the fields to change, e.g. \
{"policy": {"engage_species_allow": ["WOLF"], "flee_below_health_pct": 50}}. \
Fields: engage_species_allow (list of race strings), max_opponents (int), \
min_health_pct (int), flee_below_health_pct (int), eat_when_hungry (bool), \
drink_when_thirsty (bool), sleep_indoors_only (bool), never (list of strings).

Respond with ONLY a JSON object:
{"action": "<action_name>", "reasoning": "<brief>", "scratchpad": "<your updated notes>"}
The "scratchpad" and "policy" fields are optional; include them when they should change."""


def build_system_bundle(
    goal_summary: str | None = None,
    df_mechanics: str = "",
    postmortems: str = "",
) -> PromptBundle:
    """Static-prefix-first system bundle so providers can cache the stable part.

    Cacheable: base prompt + DF mechanics + past-life lessons (rarely change).
    Non-cacheable: goals (change on revision).
    """
    blocks: list[Block] = [Block(_SYSTEM_BASE, cacheable=True)]
    if df_mechanics:
        blocks.append(Block(f"\n--- DF Mechanics Reference ---\n{df_mechanics}\n", cacheable=True))
    if postmortems:
        blocks.append(Block(f"\n--- Session Lessons (past failures) ---\n{postmortems}\n", cacheable=True))
    if goal_summary:
        blocks.append(Block(f"\n--- Goals ---\n{goal_summary}\n", cacheable=False))
    return PromptBundle(system_blocks=blocks, user="")


def build_turn_prompt(
    state_summary: str,
    action_block: str = "",
    plan_summary: str = "",
    memory_block: str = "",
    hint: str = "",
    announcement_block: str = "",
    decision_history: str = "",
    scratchpad_block: str = "",
    screen_block: str = "",
    policy_block: str = "",
    autopilot_block: str = "",
    knowledge_block: str = "",
) -> str:
    def section(text: str) -> str:
        return f"\n{text}\n" if text else ""

    screen_section = (f"\n--- Screen Text ---\n{screen_block}\n"
                      "Use press:<KEY> or escape to navigate this screen.\n") if screen_block else ""

    return f"""\
Current game state:

{state_summary}
{section(autopilot_block)}{section(announcement_block)}{section(action_block)}{section(plan_summary)}\
{section(policy_block)}{section(scratchpad_block)}{section(decision_history)}{section(memory_block)}\
{section(knowledge_block)}{screen_section}{section(hint)}
What action do you take? Respond with a JSON object: \
{{"action": "...", "reasoning": "...", "scratchpad": "..."}}"""
